<a href="https://colab.research.google.com/github/jmohsbeck1/jpmc_mle/blob/tensorflow/jm_tf1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor flow ch 1
## 08/12/2023


## Install development version

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.12.0'

In [3]:
tensor1 = tf.Variable([2,5,7], dtype=tf.int32, name='my_tensor', trainable=True)

In [4]:
tensor1.shape

TensorShape([3])

In [5]:
tf.rank(tensor1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
int_variable = tf.Variable(365, tf.int16)
int_variable

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=365>

In [7]:
tf.rank(int_variable)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [8]:
tf.rank(int_variable).numpy()

0

In [9]:
int_variable.shape

TensorShape([])

In [10]:
int_variable.shape.as_list()

[]

In [11]:
vector_variable = tf.Variable([0.23, 0.42, 0.35], tf.float32)
vector_variable

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0.23, 0.42, 0.35], dtype=float32)>

In [12]:
tf.rank(vector_variable).numpy()

1

In [13]:
vector_variable.shape.as_list()

[3]

In [14]:
matrix_variable = tf.Variable([[41, 75, 62], [38, 67, 69]], tf.float32)
matrix_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[41, 75, 62],
       [38, 67, 69]], dtype=int32)>

In [15]:
tf.rank(matrix_variable).numpy()

2

In [16]:
matrix_variable.shape.as_list()

[2, 3]

In [17]:
tensor_variable = tf.Variable([[[41, 62, 75],[38, 67, 69]], [[51, 70, 65], [36, 59, 652]], [[95, 78, 98], [80, 45, 48]]])
tensor_variable

<tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=int32, numpy=
array([[[ 41,  62,  75],
        [ 38,  67,  69]],

       [[ 51,  70,  65],
        [ 36,  59, 652]],

       [[ 95,  78,  98],
        [ 80,  45,  48]]], dtype=int32)>

In [18]:
tf.rank(tensor_variable).numpy()

3

In [19]:
tensor_variable.shape.as_list()

[3, 2, 3]

In [20]:
int1 = tf.Variable(41, tf.int32)
int2 = tf.Variable(38, tf.int32)
int3 = tf.Variable(51, tf.int32)

In [21]:
int_sum = int1 + int2 + int3
int_sum.numpy()

130

In [23]:
vec1 = tf.Variable([41, 38, 51], tf.int32)
vec2 = tf.Variable([75, 67, 70], tf.int32)
vec3 = tf.Variable([62, 69, 65], tf.int32)

vec_sum = vec1 + vec2 + vec3

vec_sum.numpy()

array([178, 174, 186], dtype=int32)

In [24]:
print((vec1[0] + vec2[0] + vec3[0]).numpy())
print((vec1[1] + vec2[1] + vec3[1]).numpy())
print((vec1[2] + vec2[2] + vec3[2]).numpy())

178
174
186


In [26]:
matrix1 = tf.Variable([[41, 38, 51], \
                       [36, 95, 80]], tf.int32)
matrix2 = tf.Variable([[75, 67, 70], \
                       [59, 78, 45]], tf.int32)
matrix3 = tf.Variable([[62, 69, 65], \
                       [62, 98, 48]], tf.int32)

matrix1.shape == matrix2.shape == matrix3.shape

True

In [29]:
matrix_sum = matrix1 + matrix2 + matrix3
matrix_sum.numpy()

array([[178, 174, 186],
       [157, 271, 173]], dtype=int32)

In [30]:
print((matrix1[0][0] + matrix2[0][0] + matrix3[0][0]).numpy())
print((matrix1[0][1] + matrix2[0][1] + matrix3[0][1]).numpy())
print((matrix1[0][2] + matrix2[0][2] + matrix3[0][2]).numpy())
print((matrix1[1][0] + matrix2[1][0] + matrix3[1][0]).numpy())
print((matrix1[1][1] + matrix2[1][1] + matrix3[1][1]).numpy())
print((matrix1[1][2] + matrix2[1][2] + matrix3[1][2]).numpy())

178
174
186
157
271
173
