<a href="https://colab.research.google.com/github/jmohsbeck1/jpmc_mle/blob/tensorflow/jm_tf1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor flow ch 1
## 08/12/2023


## Install development version

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.12.0'

In [3]:
tensor1 = tf.Variable([2,5,7], dtype=tf.int32, name='my_tensor', trainable=True)

In [4]:
tensor1.shape

TensorShape([3])

In [5]:
tf.rank(tensor1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
int_variable = tf.Variable(365, tf.int16)
int_variable

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=365>

In [7]:
tf.rank(int_variable)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [8]:
tf.rank(int_variable).numpy()

0

In [9]:
int_variable.shape

TensorShape([])

In [10]:
int_variable.shape.as_list()

[]

In [11]:
vector_variable = tf.Variable([0.23, 0.42, 0.35], tf.float32)
vector_variable

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0.23, 0.42, 0.35], dtype=float32)>

In [12]:
tf.rank(vector_variable).numpy()

1

In [13]:
vector_variable.shape.as_list()

[3]

In [15]:
matrix_variable = tf.Variable([[41, 75, 62], [38, 67, 69]], tf.float32)
matrix_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[41, 75, 62],
       [38, 67, 69]], dtype=int32)>

In [16]:
tf.rank(matrix_variable).numpy()

2

In [17]:
matrix_variable.shape.as_list()

[2, 3]

In [18]:
tensor_variable = tf.Variable([[[41, 62, 75],[38, 67, 69]], [[51, 70, 65], [36, 59, 652]], [[95, 78, 98], [80, 45, 48]]])
tensor_variable

<tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=int32, numpy=
array([[[ 41,  62,  75],
        [ 38,  67,  69]],

       [[ 51,  70,  65],
        [ 36,  59, 652]],

       [[ 95,  78,  98],
        [ 80,  45,  48]]], dtype=int32)>

In [19]:
tf.rank(tensor_variable).numpy()

3

In [20]:
tensor_variable.shape.as_list()

[3, 2, 3]